theme = "solarized-dark"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = "echo "
on_click = '/usr/bin/call'

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "wlp5s0"
ssid = false
ip = true
speed_up = false
speed_down = false
graph_up = false
interval = 5

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%m-%d %R"
